[package]
name = "fpgrars"
version = "0.1.0"
authors = ["Leonardo Riether <leonardoalves8217@gmail.com>"]
edition = "2018"

[features]
show_ms = [] # show ms per frame in the window title

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
lazy_static = "1.4.0"
rand = "0.7.3"
iced = { git = "https://github.com/hecrj/iced", rev = "8d882d78", features = ["debug"] }
iced_native = { git = "https://github.com/hecrj/iced", rev = "8d882d78", package = "iced_native" }
pixel-canvas = "0.2.1"
glium = "0.26.0"

nom = "5.1.2"

radix_trie = "0.0.9"
fnv = "1.0.7"

byteorder = "1.3.4"